<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.zp</groupId>
    <artifactId>spring-boot-tutorial</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <description>
        spring boot tutorial
    </description>

    <properties>
        <java.version>21</java.version>
        <spring-boot.version>3.3.0</spring-boot.version>
        <redisson-spring-boot.version>3.27.0</redisson-spring-boot.version>
    </properties>
    <modules>
        <module>07-graph-springboot</module>
        <module>08-template-engine-springboot</module>
        <module>19-springboot-restful</module>
        <!-- <module>01-springboot-basic-configuration</module>
        <module>18-spring-boot-mybatis-xml</module>
        <module>40-third-config-import-bean</module>
        <module>43-activiti-spring-boot</module> -->
        <!-- <module>28-junit-springboot</module> -->
        <!-- <module>28-springboot-junit</module> -->
        <!-- <module>39-spring-boot-minio</module> -->
        <!-- <module>46-dubbo-spring-boot-demo</module> -->
         <module>47-mq-spring-boot</module>
        <!-- <module>48-ratelimiter-spring-boot</module> -->
        <!-- <module>49-thread-pool-spring-boot</module> -->
        <!-- <module>50-spring-security-learn</module> -->
        <!-- <module>51-springboot-websocket</module> -->
        <module>52-sign-spring-boot</module>
        <module>56-milvus-deeplearning4j-springboot</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
              <dependency>
                <groupId>org.mybatis.spring.boot</groupId>
                <artifactId>mybatis-spring-boot-starter</artifactId>
                 <version>3.0.3</version>
            </dependency>
            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>8.0.33</version>
            </dependency>
            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>${redisson-spring-boot.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <!-- <dependencies>
        &lt;!&ndash;        web功能起步坐标&ndash;&gt;
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        &lt;!&ndash;        热部署配置&ndash;&gt;
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <optional>true</optional>
            <scope>runtime</scope>
            &lt;!&ndash; optional=true,依赖不会传递，该项目依赖devtools；
            之后依赖myboot项目的项目如果想要使用devtools，需要重新引入 &ndash;&gt;
        </dependency>

        &lt;!&ndash;yml配置文件提示插件&ndash;&gt;
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
&lt;!&ndash;            <version>1.18.20</version>&ndash;&gt;
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <fork>true</fork>&lt;!&ndash; 如果没有该配置，热部署的devtools不生效 &ndash;&gt;
                </configuration>
            </plugin>
        </plugins>
    </build> -->


</project>