<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <!--Spring Boot启动父依赖-->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.2.RELEASE</version>
        <relativePath/>
    </parent>
    <!--指定JDK版本-->
    <properties>
        <java.version>11</java.version>
    </properties>

    <groupId>com.zp</groupId>
    <version>0.0.1-SNAPSHOT</version>
    <name>02-springboot-servlet</name>
    <description>Demo project for Spring Boot</description>
    <artifactId>02-springboot-servlet</artifactId>

    <dependencies>
        <!-- 添加springboot启动器-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>
</project>